# Generated by Django 4.2 on 2023-04-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openinghours",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("mon", "Monday"),
                    ("tues", "Tuesday"),
                    ("weds", "Wednesday"),
                    ("thurs", "Thursday"),
                    ("fri", "Friday"),
                    ("sat", "Saturday"),
                    ("sun", "Sunday"),
                ],
                max_length=10,
            ),
        ),
    ]
