# Generated by Django 4.2 on 2023-04-17 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0002_alter_openinghours_day_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openinghours",
            name="store_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opening_times",
                to="stores.store",
            ),
        ),
    ]
