# Generated by Django 4.2 on 2023-04-17 07:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stores", "0003_alter_openinghours_store_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="openinghours",
            unique_together={("store_id", "day_of_week")},
        ),
    ]
